project:
  type: website

website:
  title: "quarto-project"
  navbar:
    pinned: true
    background: light
    logo: RConsortium_Horizontal_Pantone.webp
    title: false
    logo-alt: "Quarto logo."
    right:
      - text: "Members"
        menu:
          - text: Members
            href:  members.qmd
          - text: Join
            href:  https://bugs.com
          - text: Membership Agreement
            href:  https://bugs.com

      - text: "Projects"
        menu:
          - text: Projects
            href:  projects.qmd
          - text: Funded Projects
            href:  https://bugs.com
          - text: R-Hub
            href:  https://bugs.com
          - text: R-Ladies
            href:  https://bugs.com
          - text: RUGS Program
            href:  https://bugs.com
          - text: Working Groups
            href:  https://bugs.com
          - text: R IDEA 
            href:  https://bugs.com
          - text: Submitting for payment
            href:  https://bugs.com

      - text: "About"
        menu:
          - text: About
            href:  about/about.qmd
          - text: FAQ
            href:  about/faq.qmd
          - text: Contact
            href:  about/contact.qmd
          - text: Privacy Policy
            href:  about/privacy.qmd
          - text: Governance
          - text: Bylaws
            href:  https://www.r-consortium.org/wp-content/uploads/sites/13/2024/07/Bylaws-GU-Draft-7-9-2024.docx.pdf
          - text: ICS Charter
            href:  https://www.r-consortium.org/wp-content/uploads/sites/13/2024/04/ISC-Charter-08-11-23.pdf
          - text: Marketing Committee Charter
            href:  https://www.r-consortium.org/wp-content/uploads/sites/13/2021/12/R-Consortium-Marketing-Committee-Charter-2021-10-27.pdf
      - webinars.qmd
      - r-medicine.qmd
      - text: "News"
        menu:
          - text: News
            href:  https://code.com
          - text: Events
            href:  https://bugs.com
          - text: Blog
            href:  https://code.com
          - text: Newsletter
            href:  https://bugs.com


      - codeofconduct.qmd
      - icon: github
        href: https://github.com/
      - icon: mastodon
        href: https://twitter.com
      - icon: twitter
        href: https://twitter.com
  page-footer:
    background: dark
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: Quarto Blog RSS
format:
  html:
    theme:
       - cosmo
       - cosmo.scss
    css: styles.css
execute:
  freeze: false

editor:
  render-on-save: true