project:
  type: website

website:
  title: "quarto-project"
  navbar:
    pinned: true
    background: light
    logo: RConsortium_Horizontal_Pantone.webp
    title: false
    logo-alt: "Quarto logo."
    right:
      - members.qmd
      - about.qmd
      - webinars.qmd
      - r/medicine.qmd
      - news.qmd
      - codeofconduct.qmd
      - icon: github
        href: https://github.com/
      - icon: mastodon
        href: https://twitter.com
      - icon: twitter
        href: https://twitter.com
  page-footer:
    background: dark
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: Quarto Blog RSS
format:
  html:
    theme:
       - cosmo
       - cosmo.scss
    css: styles.css
execute:
  freeze: false

editor:
  render-on-save: true