project:
  type: website

website:
  title: "quarto-project"
  navbar:
    pinned: true
    background: light
    logo: RConsortium_Horizontal_Pantone.webp
    title: false
    logo-alt: "Quarto logo."
    right:
      - text: "Members"
        menu:
          - text: Members
            href:  members.qmd
          - text: Join
            href:  join.qmd
          - text: Membership Agreement
            href:  https://www.r-consortium.org/wp-content/uploads/sites/13/2019/11/R-Consortium-Membership-Agreement-1157181-v2-Approved-11.20.19.pdf

      - text: "Projects"
        menu:
          - text: Projects
            href:  projects.qmd
          - text: Funded Projects
            href:  https://bugs.com
          - text: R-Hub
            href:  https://bugs.com
          - text: R-Ladies
            href:  https://bugs.com
          - text: RUGS Program
            href:  https://bugs.com
          - text: Working Groups
            href:  https://bugs.com
          - text: R IDEA 
            href:  https://bugs.com
          - text: Submitting for payment
            href:  https://bugs.com

      - text: "About"
        menu:
          - text: About
            href:  about/about.qmd
          - text: FAQ
            href:  about/faq.qmd
          - text: Contact
            href:  about/contact.qmd
          - text: Privacy Policy
            href:  about/privacy.qmd
          - text: Governance
            href:  governance.qmd
          - text: Bylaws
            href:  https://www.r-consortium.org/wp-content/uploads/sites/13/2024/07/Bylaws-GU-Draft-7-9-2024.docx.pdf
          - text: ICS Charter
            href:  https://www.r-consortium.org/wp-content/uploads/sites/13/2024/04/ISC-Charter-08-11-23.pdf
          - text: Marketing Committee Charter
            href:  https://www.r-consortium.org/wp-content/uploads/sites/13/2021/12/R-Consortium-Marketing-Committee-Charter-2021-10-27.pdf

      - webinars.qmd
      - r-medicine.qmd
      - text: "News"
        menu:
          - text: News
            href:  https://bugs.com
          - text: Events
            href:  https://bugs.com
          - text: Blog
            href:  https://code.com
          - text: Newsletter
            href:  newsletters/newsletters.qmd
      - codeofconduct.qmd
      - icon: github
        href: https://github.com/
      - icon: mastodon
        href: https://twitter.com
      - icon: twitter
        href: https://twitter.com
  page-footer:
    background: dark
    center: © 2024 R Consortium. © R Consortium. A [Linux Foundation](https://linuxfoundation.org) Project. R Consortium™ is a trademark of R Consortium. All Rights Reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/en/trademark-usage/) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](https://privacy-policy.r-consortium.org) and [Terms of Use](https://terms-of-use.r-consortium.org) 
format:
  html:
    theme:
       - cosmo
       - cosmo.scss
    css: styles.css
execute:
  freeze: false

editor:
  render-on-save: true