project:
  type: website

website:
  title: "R Consortium"
  favicon: rc-favicon.svg
  navbar:
    pinned: true
    background: light
    logo: RConsortium_Horizontal_Pantone.webp
    title: false
    logo-alt: "R Consortium logo"
    right:
      - text: "Members"
        menu:
          - text: "Members"
            href: members.qmd
          - text: Join
            href: about/join.qmd
          - text: Membership Agreement (PDF)
            href:  rc-docs/R-Consortium-Membership-Agreement-1157181-v2-Approved-11.20.19.pdf

      - text: "Projects"
        menu:
          - text: Projects
            href:  all-projects/index.qmd
          - text: Funded Projects
            href:  all-projects/funded-projects.qmd
          - text: Call for Proposals 
            href:  all-projects/callforproposals.qmd
          - text: R-Hub
            href:  https://github.com/r-hub
          - text: R-Ladies
            href:   https://rladies.org/
          - text: RUGS Program
            href:  all-projects/rugsprogram.qmd
          - text: Working Groups
            href:  all-projects/isc-working-groups.qmd
          - text: Submitting for payment
            href:  all-projects/submittingforpayment.qmd

      - text: "About"
        menu:
          - text: About
            href:  about/index.qmd
          - text: FAQ
            href:  about/faq.qmd
          - text: Contact
            href:  about/contact.qmd
          - text: Privacy Policy
            href:  about/privacy.qmd
          - text: Governance
            href:  about/governance.qmd
          - text: Bylaws (PDF)
            href:  rc-docs/Bylaws-GU-Draft-7-9-2024.docx.pdf
          - text: ISC Charter (PDF)
            href:  rc-docs/ISC-Charter-08-11-23.pdf
          - text: Marketing Committee Charter (PDF)
            href:  rc-docs/R-Consortium-Marketing-Committee-Charter-2021-10-27.pdf

      - ./webinars/webinars.qmd
      - text: R/Medicine
        href:  https://rconsortium.github.io/RMedicine_website/
      - text: "News"
        menu:
          - text: News
            href: news.qmd
          - text: Events
            href: news/events.qmd
          - text: Blog
            href: blog/index.qmd
          - text: Newsletter
            href:  newsletters/newsletters.qmd
      - codeofconduct.qmd
      - icon: github
        href: https://github.com/rconsortium
      - icon: linkedin
        href: https://www.linkedin.com/company/r-consortium/
      - icon: mastodon
        href: https://fosstodon.org/@RConsortium
      - icon: twitter
        href: https://x.com/RConsortium
  page-footer:
    background: dark
    center: © 2024 R Consortium. © R Consortium. A [Linux Foundation](https://linuxfoundation.org) Project. R Consortium™ is a trademark of R Consortium. All Rights Reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/en/trademark-usage/) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](https://privacy-policy.r-consortium.org) and [Terms of Use](https://terms-of-use.r-consortium.org) 
format:
  html:
    theme:
       - cosmo
       - cosmo.scss
    css: styles.css
execute:
  freeze: false

editor:
  render-on-save: true