[build]
  publish = "_site"
  command = "quarto render"

[build.environment]
  REVIEW_ID = "true"

[build.lifecycle]
  [build.lifecycle.build]
    commands = [
      "sudo apt-get update -qq",
      "sudo apt-get install -y --no-install-recommends software-properties-common dirmngr",
      "sudo add-apt-repository -y 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'",
      "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys '51716619E084DAB9'",
      "sudo apt-get update -qq",
      "sudo apt-get install -y --no-install-recommends r-base",
      "wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.335/quarto-1.2.335-linux-amd64.deb",
      "sudo dpkg -i quarto-1.2.335-linux-amd64.deb",
      "Rscript install.R",
      "quarto --version",
      "quarto render"
    ]

[[plugins]]
  package = "@quarto/netlify-plugin-quarto"
